-- pg_ash: upgrade from 1.3 to 1.4
-- ash-install.sql is safe to run on top of 1.3 (IF NOT EXISTS / CREATE OR REPLACE).
-- Changes in 1.4:
--   - Configurable N-partitions (num_partitions 3–32, rebuild_partitions())
--   - Rollup tables (rollup_1m, rollup_1h) for long-term storage
--   - Watermark-based rollup_minute(), rollup_hour(), rollup_cleanup()
--   - Rollup reader functions (minute_waits, hourly_queries, daily_peak_backends)
--   - sampling_enabled flag, skipped_samples counter, advisory lock protocol
--   - ts_from_timestamptz()/ts_to_timestamptz() epoch helpers
--   - take_sample() catches statement_timeout (missed_samples counter)
--   - Dynamic SQL in take_sample()/rotate() (replaces hardcoded 3-partition logic)
--   - Pre-truncation rollup in rotate()
--   - status() surfaces epoch_seconds_remaining for the 2094 overflow
--     horizon of sample_ts (int4). (#37)
\ir ash-install.sql
