-- pg_ash: upgrade from 1.3 to 1.4
-- ash-install.sql is safe to run on top of 1.3 (IF NOT EXISTS / CREATE OR REPLACE).
-- Changes in 1.4:
--   - Configurable N-partitions (num_partitions 3–32, rebuild_partitions())
--   - Rollup tables (rollup_1m, rollup_1h) for long-term storage
--   - Watermark-based rollup_minute(), rollup_hour(), rollup_cleanup()
--   - Rollup reader functions (minute_waits, hourly_queries, daily_peak_backends)
--   - sampling_enabled flag, skipped_samples counter, advisory lock protocol
--   - ts_from_timestamptz()/ts_to_timestamptz() epoch helpers
--   - take_sample() catches statement_timeout (missed_samples counter, #27, #28)
--   - take_sample() inner exception handler bumps insert_errors counter
--     instead of silently dropping data (M-BUG-4)
--   - _register_wait() enforces 32 000-row cap on wait_event_map; bumps
--     register_wait_cap_hits on drops (M-BUG-6 / H-SEC-3)
--   - Dynamic SQL in take_sample()/rotate() (replaces hardcoded 3-partition logic)
--   - Pre-truncation rollup in rotate()
--   - status() surfaces new counters (missed_samples, insert_errors,
--     register_wait_cap_hits) plus epoch_seconds_remaining for the 2094
--     overflow horizon of sample_ts (int4). (#37)
--   - start() validates interval shape before branching on pg_cron; re-syncs
--     cron.job.schedule on re-invocation; defends against malformed pg_cron
--     extversion. (H-BUG-1, H-BUG-2, M-BUG-8)
--   - search_path guard on every ash.* function + pgss-schema-aware readers;
--     REVOKE EXECUTE on all ash.* functions and SELECT on reader tables from
--     PUBLIC (#45).
--   - ash.grant_reader(role) / ash.revoke_reader(role) convenience helpers
--     to provision a monitoring role (Grafana, Datadog, etc.) with the
--     minimum privileges to call every public reader. Owner-only, idempotent
--     symmetric undo. (#52)
\ir ash-install.sql
