-- pg_ash: upgrade from 1.3 to 1.4
-- ash-install.sql is safe to run on top of 1.3 (IF NOT EXISTS / CREATE OR REPLACE).
-- Changes in 1.4:
--   - Configurable N-partitions (num_partitions 3–32, rebuild_partitions())
--   - Rollup tables (rollup_1m, rollup_1h) for long-term storage
--   - Watermark-based rollup_minute(), rollup_hour(), rollup_cleanup()
--   - Rollup reader functions (minute_waits, hourly_queries, daily_peak_backends)
--   - sampling_enabled flag, skipped_samples counter, advisory lock protocol
--   - ts_from_timestamptz()/ts_to_timestamptz() epoch helpers
--   - take_sample() catches statement_timeout (missed_samples counter, #27, #28)
--   - take_sample() inner exception handler bumps insert_errors counter
--     instead of silently dropping data (M-BUG-4)
--   - _register_wait() enforces 32 000-row cap on wait_event_map; bumps
--     register_wait_cap_hits on drops (M-BUG-6 / H-SEC-3)
--   - Dynamic SQL in take_sample()/rotate() (replaces hardcoded 3-partition logic)
--   - Pre-truncation rollup in rotate()
--   - status() surfaces new counters (missed_samples, insert_errors,
--     register_wait_cap_hits) plus epoch_seconds_remaining for the 2094
--     overflow horizon of sample_ts (int4). (#37)
--   - start() validates interval shape before branching on pg_cron; re-syncs
--     cron.job.schedule on re-invocation; defends against malformed pg_cron
--     extversion. (H-BUG-1, H-BUG-2, M-BUG-8)
--   - search_path guard on every ash.* function + pgss-schema-aware readers;
--     REVOKE EXECUTE on all ash.* functions and SELECT on reader tables from
--     PUBLIC (#45).
--   - decode_sample(int4) and decode_sample_at(timestamptz) convenience
--     functions: walk every ash.sample row matching a given sample_ts (or
--     the timestamptz-derived sample_ts) and return decoded rows annotated
--     with datid. Existing decode_sample(integer[], smallint) is unchanged.
--     decode_sample_at() (rather than a third decode_sample overload) is
--     used to avoid a decode_sample(unknown-typed literal) ambiguity. (#54)
--   - Reader interval-to-int4 over/underflow clamp + oversized-interval
--     short-circuit: top_waits / top_queries / top_queries_with_text /
--     top_by_type / wait_timeline / query_waits / samples_by_database /
--     samples / activity_summary / timeline_chart / event_queries (and
--     pgss variants) no longer raise `integer out of range` on absurd
--     intervals (e.g. '1000 years'). _active_slots_for() returns `{}`
--     once the interval exceeds 2 * rotation_period, so reader
--     `slot = any(...)` JOINs naturally yield empty — honoring the
--     oversized-interval NOTICE's "older samples not available" promise
--     instead of silently returning all retained data (#51).
--   - status() catches insufficient_privilege when reading cron.job so
--     non-superuser monitoring roles can call it even when pg_cron is
--     loaded (#61).
--   - ash.grant_reader(role) / ash.revoke_reader(role) convenience helpers
--     to provision a monitoring role (Grafana, Datadog, etc.) with the
--     minimum privileges to call every public reader. Owner-only, idempotent
--     symmetric undo. (#52)
--   - rebuild_partitions(p_num_partitions, p_confirm) — destructive, requires
--     p_confirm = 'yes' to proceed; old (int) overload is dropped (#53).
--   - ts_from_timestamptz() clamps to [0, INT4_MAX] so the _at reader family
--     (top_waits_at / samples_at / query_waits_at / event_queries_at /
--     timeline_chart_at / top_queries_at / wait_timeline_at / top_by_type_at /
--     minute_waits_at / hourly_queries_at / daily_peak_backends_at) no longer
--     raises `integer out of range` on absurd timestamps (pre-epoch or
--     post-2094 horizon). Pre-epoch -> 0 and post-horizon -> INT4_MAX both
--     fall outside any sample_ts window, yielding empty results — same class
--     of fix as #51 (PR #57), centralized at the helper. (#63)
--   - ash._admin_funcs() — canonical admin function list, single source of
--     truth for the REVOKE-from-PUBLIC hardening block and for
--     grant_reader/revoke_reader. Refactor; no behavior change (#67).
--   - _active_slots_for_at(p_start, p_end) helper + every range-scan
--     raw-sample _at reader (top_waits_at / top_queries_at /
--     wait_timeline_at / top_by_type_at / query_waits_at / event_queries_at /
--     timeline_chart_at / samples_at) routes its slot filter through it,
--     restoring NOTICE symmetry with _active_slots_for(p_interval): callers
--     get a loud-warn when the requested range falls outside the retained
--     window (now() - 2 * rotation_period .. now()) instead of a silent
--     empty result. The three SQL-language range readers (top_waits_at,
--     wait_timeline_at, top_by_type_at) flip to plpgsql so the helper can be
--     invoked into a local — otherwise the planner would constant-fold the
--     time predicate and skip the helper call (and its NOTICE).
--     decode_sample_at is intentionally NOT in this list: it is a
--     point-lookup keyed on an exact sample_ts, so restricting to the
--     active-slots window would hide rows the caller can prove exist in
--     other partitions. It keeps the silent ts_from_timestamptz int4 clamp
--     from #63 instead. (#69)
\ir ash-install.sql
