-- pg_ash: upgrade from 1.4 to 1.5
-- ash-install.sql is safe to run on top of 1.4 (IF NOT EXISTS / CREATE OR REPLACE / per-column ALTER guards).
-- Changes in 1.5:
--   - feat(security): ash.grant_reader(role) / ash.revoke_reader(role) helpers
--     to provision a monitoring role with the minimum privileges to call every
--     public reader. (#52, PR #60)
--   - refactor(security): canonical admin function set centralized in
--     ash._admin_funcs(); grant_reader/revoke_reader and the REVOKE-from-PUBLIC
--     hardening block all read from this single source. (#67, PR #71)
--   - safety: ash.rebuild_partitions(p_num_partitions, p_confirm) requires
--     p_confirm = 'yes' to proceed. The (int) overload is dropped on upgrade.
--     BREAKING CHANGE — existing scripts/runbooks must pass 'yes'. (#53, PR #59)
--   - feat(readers): ash.decode_sample(int4) / ash.decode_sample_at(timestamptz)
--     convenience overloads on top of the existing 2-arg packed form. The
--     timestamptz variant is named decode_sample_at to avoid a one-arg
--     ambiguity with the int4 form. (#54, PR #58)
--   - feat(readers): ash._active_slots_for_at(p_start, p_end) helper. Every
--     raw-sample _at reader (top_waits_at, top_queries_at, wait_timeline_at,
--     top_by_type_at, query_waits_at, event_queries_at, timeline_chart_at,
--     samples_at) now emits a NOTICE when the requested range falls outside
--     the retained window — symmetric with _active_slots_for(p_interval).
--     decode_sample_at is intentionally excluded (lookup, not range scan).
--     Four SQL-language readers flipped to plpgsql to keep the helper from
--     being constant-folded out. (#69, PR #72)
--   - fix(readers): clamp interval-to-int4 underflow on absurd intervals.
--     top_waits / top_queries / top_queries_with_text / top_by_type /
--     wait_timeline / query_waits / samples_by_database / samples /
--     activity_summary / timeline_chart / event_queries no longer raise
--     `integer out of range` on '1000 years'-class inputs. (#51, PR #57)
--   - fix(readers): ts_from_timestamptz() clamps to [0, INT4_MAX]; the _at
--     reader family no longer raises `integer out of range` on absurd
--     timestamps (pre-epoch or post-2094 horizon). Same class of fix as #51,
--     centralized at the helper. (#63, PR #65)
--   - fix(upgrade): align sample_data_check across upgrade paths. Existing
--     installs upgraded from 1.0 had the looser `array_length(data,1) >= 2`
--     constraint that 1.1 tightened to `>= 3`; the change was hidden by
--     `create table if not exists`. Idempotent ALTER block in install.sql
--     drops + re-adds the constraint when the legacy form is detected. (#49,
--     PR #56)
--   - fix(observability): ash.status() catches insufficient_privilege when
--     reading cron.job, so non-superuser monitoring roles can call status()
--     even when pg_cron is loaded. Returns a fallback row pointing at the
--     missing GRANT instead of erroring. (#61, PR #62)
--   - ci: end-to-end pg_cron firing test (#46, PR #73). Provisions root role +
--     root database to satisfy peer auth, runs pg_cron-actually-fires-the-
--     scheduled-job assertion, dumps cron.job/job_run_details/postgres logs
--     on failure.
--   - ci: schema-equivalence diff now includes pg_constraint. Catches the
--     class of divergence behind #49. (#66, PR #70)
--   - docs: animated demo GIF embedded in README — vanilla psql in tmux,
--     human-paced typing, colored bars, walks through the v1.4 LLM-assisted
--     investigation flow against a row-lock spike on Postgres 18. (PRs #64,
--     #68)
\ir ash-install.sql
